### ISSUE TITLE
Typo in README on how to import all modules

### ISSUE THREAD

**Issue by misha-n-ka** [vestrel00/contacts-android#106]
When I include 'com.github.vestrel00.contacts-android:0.1.7' dependency and maven repository, Android Studio warns me that it "Failed to resolve". 

But when I include 'com.github.vestrel00.contacts-android:core:0.1.7', it works.

**Comment by vestrel00** [comment]
Copy-pasting my email reply to you for visibility 😁 

Hi! Thanks for reaching out! I think I know what the issue is. I just actually found out just now based on doing research on this. I made a mistake on the documentation in the README. 

When importing modules, the syntax is correct;

```groovy
com.github.vestrel00.contacts-android:core:0.1.7
```

When importing the entire library, it should actually be;

```groovy
com.github.vestrel00:contacts-android:0.1.7
```

Notice the first “:” starts after “vestrel00”.

It’s a JitPack thing I guess =)

I would really appreciate it and I'd be happy to have you as the first contributor to the repo!!!

Thanks in advance!
