### ISSUE TITLE
Set photo did not save to system file

### ISSUE THREAD

**Issue by lau1944** [vestrel00/contacts-android#116]
After #110, I know how to get the thumbnail from your api, clap for your quick response !!!

but when i create contact, add photo using `setPhoto` api like the instruction, I could not see the photo be added to the system.   

I tested the add photo function on system dialer app, I successfully got the photo on my dialer app, so It must be the issue on the `setPhoto` part.

Here is the code I get photo uri. I am using jetpack compose.

```
val launcher = rememberLauncherForActivityResult(contract =
    ActivityResultContracts.GetContent()) { uri: Uri? ->
        imageUri = uri
    }
```

Using content provider to get photo byte data (bitmap)
```
fun uriToBitmap(context: Context, uri: Uri?) : Bitmap? {
        if (uri == null) return null

        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            ImageDecoder.decodeBitmap(
                ImageDecoder.createSource(
                    context.contentResolver,
                    uri
                )
            )
        } else {
            MediaStore.Images.Media.getBitmap(context.contentResolver, uri)
        }
    }
```

Then save the bitmap using `setPhoto` with extra contact data
```
Contacts(context)
            .insert()
            .rawContact {
                setName {
                    this.displayName = contact.name
                }
                if (!contact.email.isNullOrEmpty()) {
                    addEmail {
                        this.address = contact.email
                    }
                }
                if (!contact.location.isNullOrEmpty()) {
                    addAddress {
                        this.formattedAddress = contact.location
                    }
                }

                if (!contact.number.isNullOrEmpty()) {
                    addPhone {
                        this.number = contact.number
                    }
                }

                val photoBitmap = contact.getPhotoBitmap()
                if (photoBitmap != null) {
                    setPhoto(context, photoBitmap)
                }
            }
            .allowBlanks(true)
            .commit()
```

I check the bitmap object, it's not empty, so the problem is in the third code.

Did I do something wrong on this code ?

**Comment by vestrel00** [comment]
@lau1944, it was not clear enough so I made more updates to the documentation https://github.com/vestrel00/contacts-android/commit/8ea871ca89ef27292c77d6fb89c73bd1e8882ae0

What you are seeing is expected behavior because you are calling the `setPhoto` extension function on a RawContact that has not yet been inserted into the Contacts Provider database. You have to insert (commit) the RawContact first and then you can set the photo. 

In any case, I 100% agree that this is the fault of the library. Sorry 😁  It should not allow you to call `setPhoto` (and other extension functions) if the entity has not yet been inserted. I will be fixing this issue in #117 🔥 

For now, I added a section in this howto page to make things clear; https://github.com/vestrel00/contacts-android/blob/main/howto/howto-get-set-remove-contact-raw-contact-photo.md#inserting-contacts-with-photo

I'll copy-paste it here too.

### Inserting contacts with photo

You cannot get/set/remove photos for Contacts/RawContacts that have not yet been inserted in the 
Contacts Provider database. In other words, only Contacts/RawContacts retrieved via query or result
APIs can use the extension functions in `contacts.core.util.ContactPhoto.kt` and 
`contacts.core.util.RawContactPhoto.kt`.

To insert a new contact "with photo", you should insert the contact first. Then, if the insert 
succeeds, proceed to set the photo.

Do,

```kotlin
val insertResult = Contacts(context)
    .insert()
    .rawContact {
        ...
    }
    .commit()

val contact = insertResult.contacts(contactsApi).firstOrNull()
contact?.setPhoto(...)
```

Don't,

```kotlin
val insertResult = Contacts(context)
    .insert()
    .rawContact {
        setPhoto(...)
    }
    .commit()
```

> For more info about insert, read [How do I create/insert contacts?](/howto/howto-insert-contacts.md)

It is true that the API should not allow you to call `setPhoto` on a Contact/RawContact that has not
yet been inserted. It is currently misleading. This will be fixed in issue #117. As of right now, 
the following documentation is included in `contacts.core.util.ContactPhoto.kt` and 
`contacts.core.util.RawContactPhoto.kt` functions.

```kotlin
/*
 * ## For existing (inserted) entities only
 *
 * This function will only work for entities that have already been inserted into the Contacts
 * Provider database. This means that this is only for entities that have been retrieved using
 * query or result APIs.
 */
```

> Note for contributors; It is possible to include photo **thumbnail** data as part of the insertion
> of a new RawContact using `ContactsContract.CommonDataKinds.Photo.PHOTO`. The Contacts Provider 
> will use the thumbnail as the full-sized photo as well. However, this is not good practice as the 
> full-sized photo will have a really low resolution. Showing the full-sized photo in a big view 
> will not look good. Therefore, this library does not allow this. Consumers must first insert their
> new RawContact so that they can set the full-sized photo.

**Comment by vestrel00** [comment]
@lau1944, one more thing. I noticed in the code snippet you provided that you check if `!isNullOrEmpty()`. You actually don't need to perform that check because the API internally does not insert data that is null, empty, or blank (only spaces). You also don't need to use `this`. 

So, combined with my previous comment, your code should look something like...

```kotlin
val contactsApi = Contacts(context)
val insertResult = contactsApi
            .insert()
            .rawContact {
                setName {
                    displayName = contact.name
                }
                addEmail {
                    address = contact.email
                }
                if (!contact.location.isNullOrEmpty()) {
                    addAddress {
                        formattedAddress = contact.location
                    }
                }

                if (!contact.number.isNullOrEmpty()) {
                    addPhone {
                        number = contact.number
                    }
                }
            }
            .allowBlanks(true)
            .commit()


val photoBitmap = contact.getPhotoBitmap()
if (photoBitmap != null) {
    insertResult.contacts(contactsApi).firstOrNull()?.setPhoto(context, photoBitmap)
}
```

Also keep in mind that all of that code is being done in the caller thread and requires permissions so you might want to use the coroutine extensions provided in the library. I haven't written the howto pages for them yet but it's something like...

```kotlin
launch {
    val contactsApi = Contacts(context)
    val insertResult = contactsApi
            .insertWithPermission()
            .rawContact {
                ...
            }
            .allowBlanks(true)
            .commitWithContext()

    val photoBitmap = contact.getPhotoBitmap()
    if (photoBitmap != null) {
        insertResult
            .contacts(contactsApi)
            .firstOrNull()
            ?.setPhotoWithContext(context, photoBitmap)
    }
}
```

If you are already handling threading and permissions then you can ignore this suggestion.

Good luck! Let me know how it goes 😁

**Comment by lau1944** [comment]
Thank you for your help ! I can't believe how much effort you put in this. Clap for you 👏👏

A small suggestion for the rawContact api, to make the set method more intuitive, 
Instead of disabling the set photo method in the rawContact scope function, you can add photo after the contact has been successfully committed to the library. 
The developer doesn't have to worry much about two insertResult states, the first is contact insert result, second is photo add result, you handle that in your library, and it looks much cleaner in our view.

**Comment by vestrel00** [comment]
Thanks for that suggestion @lau1944 !!! ❤️ 🔥 

I thought about this a lot. At first, I was thinking of all the reasons why I should not take your suggestion. Things like, API complexity, maintenance costs, supporting multiple ways of doing the same thing, all came to my mind. I thought to myself, "no".

However, when I look at it from a consumer perspective (your perspective) I 100% agree with you. At the end of the day, this library is about making it easier for consumers to interface with the Contacts Provider. It is not about how beautifully architected the library is (though I will keep it beautiful as much as I can 😁).

So, I created issues #119 and #120.

Thanks again for your valuable feedback!!! And of course, thanks for trying out this library. I'm having a lot of fun working on this haha!

**Comment by lau1944** [comment]
Looking forward to your work 😊
