### ISSUE TITLE
Query where "and" operation with multiple data fields that have different mimetypes are not working

### ISSUE THREAD

**Issue by alorma** [vestrel00/contacts-android#142]
Code example:

Using filters:

<img width="464" alt="Captura de pantalla 2021-12-21 a las 19 54 07" src="https://user-images.githubusercontent.com/887462/146983371-00b70ac6-cf02-44a8-abba-701281212fbf.png">

```
contacts
      .query()
      .where(filters whereAnd { it.isNotNullOrEmpty() })
      .include(
        Fields.Contact.Id,
        Fields.Contact.DisplayNamePrimary,
        Fields.Email.Address,
        Fields.Phone.Number,
        Fields.Address.FormattedAddress,
      )
.findWithContext()
```

It returns an empty list, and I have contacts with both, email and phone...

**Comment by vestrel00** [comment]
This could be happening if query permission has not yet been granted. All queries will return an empty list if permission is not granted.

To make sure that this is a bug, could you change `query()` to `queryWithPermission()` and see if that fixes the issue?

If it does not fix the issue, could you please share relevant parts of your local Contacts database? You can use the `Context.logContactsProviderTables()` extension function to log all of the Contacts, RawContacts, and Data that is in your device in the Logcat. Then, copy and paste that into this issue so I can see what's going on. If you have contact info that you do not want to share or make public, you should make some fake contacts that have email AND phone.

Related readings; [How do I debug the Contacts Provider tables?](https://github.com/vestrel00/contacts-android/blob/main/howto/howto-debug-contacts-provider-tables.md)

**Comment by alorma** [comment]
Hi.

No, permissions are already granted, both with `queryWithPermissions()` or by other methods prior to load list.

If filters list is empty, or just contains a single filter it returns a non empty list. Combination of multiple fields return an empty list

**Comment by alorma** [comment]
For sure! I will try log tomorrow

**Comment by alorma** [comment]
Contact table log:

```
D/ContactsDebug: #### Groups table
D/ContactsDebug: #### Aggregation exceptions table
D/ContactsDebug: #### Profile
D/ContactsDebug: #### Contacts table
D/ContactsDebug: Contact id: 1, displayNamePrimary: User 1, displayNameAlt: User 1, starred: 0, customRingtone: null, sendToVoicemail: 0, photoFileId: null, photoUri: null, photoThumbnailUri: null, hasPhoneNumber: 1
D/ContactsDebug: #### RawContacts table
D/ContactsDebug: RawContact id: 1, contactId: 1, displayNamePrimary: User 1, displayNameAlt: User 1,  accountName: null, accountType: null, starred: 0, customRingtone: null, sendToVoicemail: 0
D/ContactsDebug: #### Data table
D/ContactsDebug: Data id: 1, rawContactId: 1, contactId: 1, mimeType: vnd.android.cursor.item/phone_v2, isPrimary: 0, isSuperPrimary: 0, data1: 661 12 34 67, data2: 2, data3: null, data4: null, data5: null, data6: null, data7: null, data8: null, data9: null, data10: null, data11: null, data12: null, data13: null, data14: null
D/ContactsDebug: Data id: 2, rawContactId: 1, contactId: 1, mimeType: vnd.android.cursor.item/email_v2, isPrimary: 0, isSuperPrimary: 0, data1: user1@gmail.com, data2: 1, data3: null, data4: null, data5: null, data6: null, data7: null, data8: null, data9: null, data10: null, data11: null, data12: null, data13: null, data14: null
D/ContactsDebug: Data id: 3, rawContactId: 1, contactId: 1, mimeType: vnd.android.cursor.item/name, isPrimary: 1, isSuperPrimary: 1, data1: User 1, data2: User 1, data3: null, data4: null, data5: null, data6: null, data7: null, data8: null, data9: null, data10: 1, data11: 0, data12: null, data13: null, data14: null

```

**Comment by vestrel00** [comment]
😮 it seems like it should work 😓 I'll try to reproduce the issue tomorrow!

One more thing you can do to help me. Please log the query as a string and paste it here so I can see it.

So...

```kotlin
contacts
      .query()
      .where(filters whereAnd { it.isNotNullOrEmpty() })
      .include(...)
      .apply {
          Log.d("QUERY", it.toString())
      }
     .findWithContext()

```

**Comment by alorma** [comment]
About logging... I have an idea, I will open an issue about that

**Comment by alorma** [comment]
Query with NO filters:

```
Query {
        includeBlanks: true
        rawContactsWhere: null
        include: contact_id, display_name, data1, _id, raw_contact_id, mimetype, is_primary, is_super_primary
        where: null
        orderBy: display_name COLLATE NOCASE ASC
        limit: 2147483647
        offset: 0
    }
```

Query with ONE filter:

```
Query {
        includeBlanks: true
        rawContactsWhere: null
        include: contact_id, display_name, data1, _id, raw_contact_id, mimetype, is_primary, is_super_primary
        where: ((data1 IS NOT NULL AND mimetype = 'vnd.android.cursor.item/email_v2') AND (data1 != '' AND mimetype = 'vnd.android.cursor.item/email_v2'))
        orderBy: display_name COLLATE NOCASE ASC
        limit: 2147483647
        offset: 0
    }
```

Query with TWO filters:

```
Query {
        includeBlanks: true
        rawContactsWhere: null
        include: contact_id, display_name, data1, _id, raw_contact_id, mimetype, is_primary, is_super_primary
        where: ((data1 IS NOT NULL AND mimetype = 'vnd.android.cursor.item/email_v2') AND (data1 != '' AND mimetype = 'vnd.android.cursor.item/email_v2')) AND ((data1 IS NOT NULL AND mimetype = 'vnd.android.cursor.item/phone_v2') AND (data1 != '' AND mimetype = 'vnd.android.cursor.item/phone_v2'))
        orderBy: display_name COLLATE NOCASE ASC
        limit: 2147483647
        offset: 0
    }
```

**Comment by vestrel00** [comment]
@alorma, I was able to reproduce the issue 🔥  I can't believe I missed it! I remember in the past having issue making "and" statements work. Anyways, thank you for raising this issue ❤️ 

I changed the title of this issue now that I know the exact cause. To be clear, this issue is specific to the `Query` API. You will not be able to reproduce this issue in the other query APIs. You will also not be able to reproduce the issue if you only use "OR"...

✅ The "OR" operator will work as expected in all cases.

```kotlin
.where (Fields.Email.Address.isNotNull() or Fields.Phone.Number.isNotNull())
```

✅ The "AND" operator will work as expected **when using fields with the same or no mime type**.

```kotlin
.where ((Fields.Email.Address startsWith "a") and (Fields.Email.Address endsWith "gmail.com"))
```

❌  The "AND" operator will NOT work as expected **when using fields with different mime types**.

```kotlin
.where ((Fields.Email.Address startsWith "a") and (Fields.Phone.Number endsWith "0"))
```

### Context

As stated in [How do I learn more about the API entities?](https://github.com/vestrel00/contacts-android/blob/main/howto/howto-learn-more-about-api-entities.md#contacts-provider--contactscontract-basic-concept), the Data for each RawContact and the associated Contact all live in different tables.

The `Query` API queries the **Data** table to match **Contacts** using the specified rules in the `where` clause. In other words, we are trying to match entities in a table by querying a different table and relying on the implicit indirect relationship between them. I have written the APIs in this library with this in mind. However, I apparently missed this important case that led to this issue 🤣 

Anyways, here is the breakdown of the problem and solution!

### Problem

Given the following tables,

```
D/ContactsDebug: #### Contacts table
D/ContactsDebug: Contact id: 1, displayNamePrimary: User 1, displayNameAlt: User 1, starred: 0, customRingtone: null, sendToVoicemail: 0, photoFileId: null, photoUri: null, photoThumbnailUri: null, hasPhoneNumber: 1
D/ContactsDebug: #### RawContacts table
D/ContactsDebug: RawContact id: 1, contactId: 1, displayNamePrimary: User 1, displayNameAlt: User 1,  accountName: null, accountType: null, starred: 0, customRingtone: null, sendToVoicemail: 0
D/ContactsDebug: #### Data table
D/ContactsDebug: Data id: 1, rawContactId: 1, contactId: 1, mimeType: vnd.android.cursor.item/phone_v2, isPrimary: 0, isSuperPrimary: 0, data1: 661 12 34 67, data2: 2, data3: null, data4: null, data5: null, data6: null, data7: null, data8: null, data9: null, data10: null, data11: null, data12: null, data13: null, data14: null
D/ContactsDebug: Data id: 2, rawContactId: 1, contactId: 1, mimeType: vnd.android.cursor.item/email_v2, isPrimary: 0, isSuperPrimary: 0, data1: user1@gmail.com, data2: 1, data3: null, data4: null, data5: null, data6: null, data7: null, data8: null, data9: null, data10: null, data11: null, data12: null, data13: null, data14: null
D/ContactsDebug: Data id: 3, rawContactId: 1, contactId: 1, mimeType: vnd.android.cursor.item/name, isPrimary: 1, isSuperPrimary: 1, data1: User 1, data2: User 1, data3: null, data4: null, data5: null, data6: null, data7: null, data8: null, data9: null, data10: 1, data11: 0, data12: null, data13: null, data14: null
```

the `Query` API will return no results when using the following `where` statement,

```kotlin
.where (Fields.Email.Address.isNotNull() and Fields.Phone.Number.isNotNull())
```

**because it is impossible to have a row in the Data table that represents both an email and a phone number!**

The data table contains pieces of a RawContact's information such as name, phone, email, etc. Each row in the Data table represents a particular kind of data as indicated by the value in the mime type column. *Note that the generic column names "data1", "data2", etc have nothing to do with this issue.*

Let me simplify the problem even further.

```
Data row 1, email=...
Data row 2, phone=...
```

Using the where statement,

```
email AND phone exist
```

will yield no results because,

- `Data row 1` has email info but not phone info
- `Data row 2` has phone info but not email info

There is no data row that contains both email and phone info. This is the expected result for this single query and would have been the correct result if we were only interested in matching rows in the Data table. However, it is an incorrect result because we are trying to match rows in the Contacts table.

### Solution

Internally perform a Data table query for each statement in the `where` clause that;

- are combined using "AND" 
- when the mime types are different.

> Evaluating `Where` to support this case is now possible due to the work done in #149. It is all connected!!! I'm excited 😁

For example,

```kotlin
.where (Fields.Email.Address.isNotNull() and Fields.Phone.Number.isNotNull())
```

instead of performing a single query that would yield no results, two queries will be performed **internally**. Traversing the binary tree structure of `Where` will allow us to reduce each part of the above `where` clause to  contact IDs. The where clause will keep getting reduced until it can no longer be reduced.
 
Sequential reduction would look something like...

```kotlin
original -> Fields.Email.Address.isNotNull() and Fields.Phone.Number.isNotNull()
reduce -> Fields.Contact.Id.in(contactIdsWithEmail) and Fields.Phone.Number.isNotNull()
```

The original query will work after performing just one reduction, which is to query for the results of `Fields.Email.Address.isNotNull()`. The `Fields.Contact.Id` exist for all rows in the Data table, including phone data rows.

Another more complex example...

```kotlin
original -> (Email and Phone) and (Organization or Website)
reduce -> (ContactIDs and Phone) and (Organization or Website)
reduce -> (ContactIDs and ContactIDs) and (Organization or Website)
```

Two queries are required to reduce the original query into something that will work.

It's probably going to be a bit more complicated than because `Where`s can be large and complex that but the gist of how to solve the problem is there.

**Consumer API and usage should be unaffected.** The issue will simply go away after making internal change 😄

**Comment by alorma** [comment]
Wow.

I declare myself fan of your work.

It's such a great pleasure to raise issues on open source code that has so much effort and attention to details.

Thank you!

**Comment by vestrel00** [comment]
Thanks! I'm doing this for the community and myself. One of the things I want to accomplish in life is to give back to the Android community. I wouldn't be where I am now in life if it were not for Android ❤️

**Comment by vestrel00** [comment]
Time to finally get to working on this!! At last! 🔥

**Comment by vestrel00** [comment]
@alorma, I have fixed this bug! Starting with [v0.2.0](https://github.com/vestrel00/contacts-android/discussions/146), your queries will work!

Any of the following will work 🔥 

```kotlin
.where { Email.Address.isNotNull() and Phone.Number.isNotNull() and Name.DisplayName.isNotNull() and Organization.Company.isNotNull() }
```

**Comment by alorma** [comment]
Woooho!

**Comment by vestrel00** [comment]
This is released in https://github.com/vestrel00/contacts-android/releases/tag/0.2.0
