### ISSUE TITLE
Suggestion: Maybe Implement PREFERRED_PHONE_ACCOUNT_ID

### ISSUE THREAD

**Issue by NLLAPPS** [vestrel00/contacts-android#245]
As per https://developer.android.com/reference/android/provider/ContactsContract.DataColumns#PREFERRED_PHONE_ACCOUNT_ID

**Comment by vestrel00** [comment]
@NLLAPPS based on my preliminary investigations, the `PREFERRED_PHONE_ACCOUNT_ID` is used by dialer apps in conjunction with `PhoneAccountHandle` and `PhoneAccount`. All of these have been recently introduced in Android API 28. It seems like an advanced feature that is very specific for dialer apps (mainly dealing with `TelecomManager`), which I'm currently not prioritizing. 

![Screen Shot 2022-07-06 at 10 51 44 AM](https://user-images.githubusercontent.com/4332753/177641036-84214a93-d612-4f0f-a552-82fa7520d0fb.png)
![Screen Shot 2022-07-06 at 10 51 52 AM](https://user-images.githubusercontent.com/4332753/177641047-fbaa04cf-b67e-4599-a036-cac2dfb
![Screen Shot 2022-07-06 at 10 51 58 AM](https://user-images.githubusercontent.com/4332753/177641060-079e9a54-14e4-4e43-bb6f-29bb4978a952.png)
501b4.png)

I can certainly add in that field as part of the `Phone` entity but I'm not sure what exactly it is used for and how. It's going to take me days to investigate and document. It's probably related to a bunch of other things as I pointed out above. 

I'll wait to add this until I get more time to investigate and until I complete more higher priority issues in the **[Project Roadmap](https://github.com/vestrel00/contacts-android/wiki/Project-Roadmap#additional-features-for-v1)**.

For now, I will convert this to a discussion so that other people can participate if they are also interested 😁 

Thanks!
