### ISSUE TITLE
ExistingContactEntity.setPhotoDirect fails when there is no previous photo

### ISSUE THREAD

**Issue by reactormonk** [vestrel00/contacts-android#289]
The code in `ContactPhoto.kt` expects an existing photo, otherwise it'll fail:

https://github.com/vestrel00/contacts-android/blob/main/core/src/main/java/contacts/core/util/ContactPhoto.kt#L381-L387

`photoFileId` will always be null without an existing photo.

**Comment by vestrel00** [comment]
Lol. Nice catch! 🤦 It seems like this is regression. I broke this in this commit, https://github.com/vestrel00/contacts-android/commit/253ced838491b33bf71322668954e17d9ba58232

**Comment by vestrel00** [comment]
Btw, this bug is specific to `ExistingContactEntity`. It does not apply to `ExistingRawContactEntity` (`RawContactPhoto.kt`). So, I updated the issue title to reflect this.

**Comment by vestrel00** [comment]
@reactormonk, this is fixed in [0.3.1](https://github.com/vestrel00/contacts-android/discussions/288). I will not be releasing it any time soon since I want to include more issues in that release.

If you must set the photo of an `ExistingContactEntity` using versions `0.3.0` and lower, use `setPhoto` in conjunction with the `Update` API instead of `setPhotoDirect`. Instructions are at https://vestrel00.github.io/contacts-android/other/get-set-remove-contact-raw-contact-photo/#as-part-of-an-insert-or-update-api-call

Thanks so much for raising this bug! ❤️ 🙏 🙇

**Comment by vestrel00** [comment]
🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥 
This is now release in [0.3.1](https://github.com/vestrel00/contacts-android/releases/tag/0.3.1)!
🔥 🔥 🔥 🔥 🔥 🔥 🔥 🔥
