### ISSUE TITLE
Add ability to create our own SimContact from scratch

### ISSUE THREAD

**Issue by lt692** [vestrel00/contacts-android#335]
Add ability to construct Entities.
e.g:

// i would provide needed variables from Flutter method channel.
 val current = SimContact(
      id = 1, 
      name = "John Doe",
      number = "1234567890",
      isRedacted = false
  )

  var modified: MutableSimContact = current.mutableCopy {
      number = "123",
  }

  val updateResult = Contacts(context)
      .sim()
      .update()
      .simContact(current, modified)
      .commit()

**Comment by vestrel00** [comment]
Hey @lt692, I have been intentionally doing my best to disallow users of these APIs from constructing their own entities in order to maintain data integrity as much as possible.

Creating your own immutable entities (the same ones returned by query APIs) from scratch is not something I would want to add support for, even though it is trivial. It would give users of this library many different ways to deal with contacts in the wrong way, which I'm attempting to prevent.

With all that said, please perform a query to retrieve the SimContact that you wish to update, and then create a mutable copy from that to perform the update.

I'm closing this issue. Thanks in advance for understanding 🙏

**Comment by lt692** [comment]
I understand. I will kindly ask for your help to implement that feature to forked repo. I am not familiar with Kotlin language and for you adding a simple constructor for my case would help a ton! Will you help me out? ❤️

**Comment by vestrel00** [comment]
Sure! If it's just making a constructor visible to consumers, that's a one line code change. I'd be happy to help =)

**Comment by vestrel00** [comment]
I made the changes in your fork. LMK if it works!

https://github.com/lt692/contacts-android/commit/7cbe1520d950c09a0512bc2544c41fa2ef9b44d4

**Comment by lt692** [comment]
> I made the changes in your fork. LMK if it works!
> 
> [lt692@7cbe152](https://github.com/lt692/contacts-android/commit/7cbe1520d950c09a0512bc2544c41fa2ef9b44d4)

It works, thank you again. Now it lets me create SimContact object, but did not try to insert anything yet to SIM. 
Before that i wanted to figure out multi SIM case. 
Like you stated in docs not sure if it works. 
Current code fetches the main (i think 1st) SIM contacts. But you can change the URI with proper one and it fetches contacts from. I will add which url i used later if needed. Currently sick in bed 🤕

**Comment by vestrel00** [comment]
Thanks for the update! I created an issue for supporting multi-SIM card devices. Thanks for sharing your findings!

https://github.com/vestrel00/contacts-android/issues/336

Note that I created the issue but I have no plans on working on it anytime soon unless it's becomes popular demand from the community. Or, when I get some time when things cool down with work and tech layoffs in general 😁
