### ISSUE TITLE
How to use the RawContact SOURCE_ID in Java?

### ISSUE THREAD

**Issue by lati111** [vestrel00/contacts-android#351]
I'm currently implementing this in an old app that is still built with plain android Java. I need to pull and update contacts from the database, and would like to implement an ID field taken from the database to avoid duplicates, since that's the only unique piece of data on the contacts from the database. 

Unfortunately, the documentation for custom data is very complex, and the differences between java and kotlin are rather extreme for those, leaving me unable to easily convert them. Would it be possible to provide an example or documentation for Java on that component (or have a way to implement this that I missed in the documentation)? 

If that's too much of a hassle that's totally fair, if unfortunate. Thanks in advance and keep up the good work!

**Comment by vestrel00** [comment]
> Would it be possible to provide an example or documentation for Java on that component (or have a way to implement this that I missed in the documentation)?

Yes! I'd love to help you here. I agree that custom data integration is the one thing in this library that is completely lacking documentation and examples in Java. As a a matter of fact, I do not even know myself what the Java developer experience would be for this and if I even wrote custom data stuff to work with Java at all 😅

Anyways, this would be a perfect opportunity to make sure that custom data is usable in Java! 

Here's what I'll do. I'll implement the custom data code purely in Java in the `sample` app module of this repo so that you and others may use it for reference (and I get to make sure it works in Java).

However, I will need to know more details about what you are trying to implement.

**Comment by vestrel00** [comment]
> I need to pull and update contacts from the database, and would like to implement an ID field taken from the database to avoid duplicates, since that's the only unique piece of data on the contacts from the database.

Could you give me more details on what this ID field is? I assume that there can only be one value for this ID field per RawContact correct? What would you name this field? 

Could you give me an example of how you would be using this? Pseudocode would be fine.

**Comment by lati111** [comment]
> > Would it be possible to provide an example or documentation for Java on that component (or have a way to implement this that I missed in the documentation)?
> 
> Yes! I'd love to help you here. I agree that custom data integration is the one thing in this library that is completely lacking documentation and examples in Java. As a a matter of fact, I do not even know myself what the Java developer experience would be for this and if I even wrote custom data stuff to work with Java at all 😅
> 
> Anyways, this would be a perfect opportunity to make sure that custom data is usable in Java!
> 
> Here's what I'll do. I'll implement the custom data code purely in Java in the `sample` app module of this repo so that you and others may use it for reference (and I get to make sure it works in Java).
> 
> However, I will need to know more details about what you are trying to implement.

That's wonderful to hear and much appreciated!

For my specific use case I have an API for my company's internal portal, which as a list of client contact information which we want automatically synched to the phone's contact list using our work app. I've written the sync adapter and API stuff and that works perfectly. 
For the actual importing however, I need to be able to check if that contact already exists before adding or updating it. The main issue here is that every common piece of data about a contact (from the api) can change meaning that a name or a phone number is not identifiable information. 
For this I want to use the internal code assigned to each contact person in the API (in this case a uuid string) as a field hidden in the regular android contacts app. That way I can look up if a contact with that uuid already exists in the user's phone and update it instead of creating a new one. 



> > I need to pull and update contacts from the database, and would like to implement an ID field taken from the database to avoid duplicates, since that's the only unique piece of data on the contacts from the database.
> 
> Could you just use the Contact's or RawContact's ID? Those should be unique.
> 
> Could you give me more details on what this ID field is? I assume that there can only be one value for this ID field per RawContact correct? What would you name this field?
> 
> Could you give me an example of how you would be using this? Pseudocode would be fine.

Unless I misintepreted the information, there doesn't seem to be a way to assign either of those IDs, as they seem automatically generated by android. This means that each phone would have a different ID for the imported contact, which means I wouldn't be able to check if they exist on the user's phone as the api wouldn't know the local ID for that contact.

As for pseudo code, here it more or less is 

```
List<ContactInfo> contactList = new List<ContactInfo>

// Fill contactList with contacts from the portal's database through an API call
this.api.getApiContacts(contactList);

// Loop through all contacts to make the local contacts match the imported ones
for (ContactInfo contactData : contactList ) {
  // Check if a contact exists with the uuid taken from the imported contact
  List<Contact> contacts = Contacts.Query.Where(Uuid, "=", contactData.uuid).find();
  
  if (result.size() > 0) {
    // If a contact with that uuid does exists, update it with the imported data, making sure uuid remains the same
    this.updateContact(contacts[0], contactData);
    continue;
  }

  // This method would create and insert a contact with the given data making sure to specify the uuid
  this.createContact(contactData); 
}
```

Let me know if you need any more info, and thanks for the quick response and support!

**Comment by vestrel00** [comment]
I see! I think I understand what the problem is now. Essentially, you need to have a UUID for each RawContact in the **local** (on phone) Contacts Provider database that contains the same values as the ones you are storing in your **remote** api/database. This will allow you to locate local and remote RawContacts and keep them in sync, which is critical for sync adapters. 

If I understood that correctly, then I believe that this is already supported by the current version of this library. You do not need to implement custom data for this. It is built into the Android Contacts Provider.

I believe your use case is the same as #299, which I implemented in #300, and released as part of version [0.3.1](https://github.com/vestrel00/contacts-android/releases/tag/0.3.1).

I unfortunately did not write much documentation around sync adapter use cases because I did not build this library with that focus in mind.  However, I do have some documentation that might help you. Please take a look at the following documentation and support I added for `ContactsContract.SyncColumns.SOURCE_ID`;

- https://github.com/vestrel00/contacts-android/blob/0.3.1/core/src/main/java/contacts/core/entities/RawContact.kt#L171-L216
- https://vestrel00.github.io/contacts-android/entities/about-contact-lookup-key/  (search for mentions of `SOURCE_ID` and `sourceId`
- https://vestrel00.github.io/contacts-android/setup/setup-contacts-api/#sync-adapter-operations

As of version `0.3.1`, you are able to set the value of the RawContact's `SOURCE_ID` in inserts or updates. You are also able to use the `RawContactsFields.SourceId` to [Query RawContacts](https://vestrel00.github.io/contacts-android/basics/query-raw-contacts/) and match based on that field. 

-------

If you have already considered the RawContact's `SOURCE_ID` and it is not what you are looking for, then I will proceed to implement the custom data in the `sample` app. Let me know! 😄

**Comment by vestrel00** [comment]
I have some Java samples that includes import statements in the cheat sheet; https://vestrel00.github.io/contacts-android/cheatsheet/#query-for-rawcontacts

Make sure to switch to Java code samples since it defaults to showing Kotlin.

Here's what it might look like for you;

```Java


List<RawContact> getRawContacts() {
    List<Account> accounts = new ArrayList<>();
    accounts.add(yourSyncAdapterAccount);

    return ContactsFactory.create(this)
        .rawContactsQuery()
        .rawContactsWhere(
            accounts,
            equalTo(RawContactsFields.SourceId, "uuidyoukeepinyourremotedatabase")
                )
        .find();
    }
```

**Comment by lati111** [comment]
> I have some Java samples that includes import statements in the cheat sheet; https://vestrel00.github.io/contacts-android/cheatsheet/#query-for-rawcontacts
> 
> Make sure to switch to Java code samples since it defaults to showing Kotlin.
> 
> Here's what it might look like for you;
> 
> ```java
> List<RawContact> getRawContacts() {
>     List<Account> accounts = new ArrayList<>();
>     accounts.add(yourSyncAdapterAccount);
> 
>     return ContactsFactory.create(this)
>         .rawContactsQuery()
>         .rawContactsWhere(
>             accounts,
>             equalTo(RawContactsFields.SourceId, "uuid")
>         )
>         .find();
>     }
> ```
> 
> Go to the cheat sheet page I linked for the import statements 😁

Ah there it is yeah, I was mostly looking at the basics and data tabs during my search. Thanks for all the help! I'll give it a try tomorrow at the office and let you know if it works and close out the issue. 

Does the project have a donation page of some kind? I'd like to drop a few bucks in thanks for the quick support and the general usefulness of the project (not having to much around in basic java contacts is a literal godsend). Thanks again!

**Comment by vestrel00** [comment]
I don't take donations. I work on this project solely to give back to the Android community ❤️

However, I would greatly appreciate it if you starred ⭐ the repo 😁

Anyways, let me know if it works out!

**Comment by lati111** [comment]
> I don't take donations. I work on this project solely to give back to the Android community ❤️
> 
> However, I would greatly appreciate it if you starred ⭐ the repo 😁
> 
> Anyways, let me know if it works out!

Totally fair, I did star the repo and will let you know the results tomorrow!

**Comment by lati111** [comment]
Yep, that works just as wanted! Thanks again for the support, I'll close out the issue.
